server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
     name: HOTEL-SERVICE  
   
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice  # Ensure the database 'microservice' exists
    username: postgres
    password: jayesh004

eureka:
  instance:
    prefer-ip-address: true 

  client:
    fetch-registry: true 
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka    
   
